package latheadapt

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"time"
)

const (
	InstallHint = "install Lathe: go install github.com/lathe-cli/lathe/cmd/lathe@v0.5.2  (or download a release from https://github.com/lathe-cli/lathe/releases)"
	PinVersion  = "v0.5.2"
)

type GenerateOptions struct {
	Name        string
	OpenAPIPath string // absolute or relative path to OpenAPI file
	OutDir      string // project root for Lathe CLI
	ModulePath  string // go module path for OutDir; default derived
	Short       string
	LatheBin    string // optional override
	SkipBuild   bool
	Timeout     time.Duration
}

type GenerateResult struct {
	OutDir       string
	LatheBinary  string // path to built Lathe CLI (bin/<name>)
	WrapBinary   string // path to Helios wrapper source dir
	Introspect   string // path to written introspect.json
	CatalogJSON  string
	CLIName      string
}

// LookPathLathe finds lathe on PATH.
func LookPathLathe() (string, error) {
	p, err := exec.LookPath("lathe")
	if err != nil {
		return "", fmt.Errorf("lathe not found on PATH; %s", InstallHint)
	}
	return p, nil
}

// Generate scaffolds a Lathe project, runs codegen, builds, writes Helios wrapper + introspect.
func Generate(ctx context.Context, opts GenerateOptions) (GenerateResult, error) {
	if strings.TrimSpace(opts.Name) == "" {
		return GenerateResult{}, fmt.Errorf("name is required")
	}
	for _, r := range opts.Name {
		if (r < 'a' || r > 'z') && (r < '0' || r > '9') && r != '-' {
			return GenerateResult{}, fmt.Errorf("name must be lowercase alphanumeric with hyphens")
		}
	}
	if opts.OpenAPIPath == "" {
		return GenerateResult{}, fmt.Errorf("openapi path is required for engine=lathe")
	}
	if opts.OutDir == "" {
		return GenerateResult{}, fmt.Errorf("out dir is required")
	}
	absOpenAPI, err := filepath.Abs(opts.OpenAPIPath)
	if err != nil {
		return GenerateResult{}, err
	}
	if _, err := os.Stat(absOpenAPI); err != nil {
		return GenerateResult{}, fmt.Errorf("openapi file: %w", err)
	}
	absOut, err := filepath.Abs(opts.OutDir)
	if err != nil {
		return GenerateResult{}, err
	}
	if opts.Timeout <= 0 {
		opts.Timeout = 3 * time.Minute
	}
	ctx, cancel := context.WithTimeout(ctx, opts.Timeout)
	defer cancel()

	latheBin := opts.LatheBin
	if latheBin == "" {
		latheBin, err = LookPathLathe()
		if err != nil {
			return GenerateResult{}, err
		}
	}
	mod := opts.ModulePath
	if mod == "" {
		mod = "github.com/Duang777/helios/backend/" + filepath.Base(absOut)
	}
	short := opts.Short
	if short == "" {
		short = opts.Name + " (Lathe-generated Helios CLI)"
	}

	if err := os.MkdirAll(absOut, 0o755); err != nil {
		return GenerateResult{}, err
	}
	openapiDir := filepath.Join(absOut, "openapi")
	if err := os.MkdirAll(openapiDir, 0o755); err != nil {
		return GenerateResult{}, err
	}
	destSpec := filepath.Join(openapiDir, "openapi"+extOf(absOpenAPI))
	raw, err := os.ReadFile(absOpenAPI)
	if err != nil {
		return GenerateResult{}, err
	}
	if err := os.WriteFile(destSpec, raw, 0o644); err != nil {
		return GenerateResult{}, err
	}

	if err := writeFile(filepath.Join(absOut, "go.mod"), fmt.Sprintf("module %s\n\ngo 1.23\n", mod)); err != nil {
		return GenerateResult{}, err
	}
	cliYAML := fmt.Sprintf(`cli:
  name: %s
  short: %q
auth:
  default_type: bearer
skill:
  root: skills
  bundle: false
`, opts.Name, short)
	if err := writeFile(filepath.Join(absOut, "cli.yaml"), cliYAML); err != nil {
		return GenerateResult{}, err
	}
	if err := os.MkdirAll(filepath.Join(absOut, "specs"), 0o755); err != nil {
		return GenerateResult{}, err
	}
	sources := `sources:
  api:
    local_path: ../openapi
    backend: openapi3
    openapi3:
      files:
        - ` + filepath.Base(destSpec) + `
`
	if err := writeFile(filepath.Join(absOut, "specs", "sources.yaml"), sources); err != nil {
		return GenerateResult{}, err
	}

	cmdDir := filepath.Join(absOut, "cmd", opts.Name)
	if err := os.MkdirAll(cmdDir, 0o755); err != nil {
		return GenerateResult{}, err
	}
	if err := writeFile(filepath.Join(cmdDir, "cli.yaml"), cliYAML); err != nil {
		return GenerateResult{}, err
	}
	mainGo := fmt.Sprintf(`// Code generated by helios-factory (engine=lathe). DO NOT EDIT.
package main

import (
	_ "embed"
	"os"

	"github.com/lathe-cli/lathe/pkg/lathe"

	"%s/internal/generated"
)

//go:embed cli.yaml
var manifestBytes []byte

func main() {
	os.Exit(lathe.Run(lathe.RunOptions{
		Manifest: manifestBytes,
		Mount:    generated.MountModules,
	}))
}
`, mod)
	if err := writeFile(filepath.Join(cmdDir, "main.go"), mainGo); err != nil {
		return GenerateResult{}, err
	}

	if err := run(ctx, absOut, latheBin, "bootstrap"); err != nil {
		return GenerateResult{}, err
	}
	if err := run(ctx, absOut, "go", "mod", "tidy"); err != nil {
		return GenerateResult{}, err
	}

	binDir := filepath.Join(absOut, "bin")
	if err := os.MkdirAll(binDir, 0o755); err != nil {
		return GenerateResult{}, err
	}
	latheOut := filepath.Join(binDir, opts.Name+".lathe")
	if !opts.SkipBuild {
		if err := run(ctx, absOut, "go", "build", "-o", latheOut, "./cmd/"+opts.Name); err != nil {
			return GenerateResult{}, err
		}
	}

	catalogPath := filepath.Join(absOut, "helios-catalog.json")
	introPath := filepath.Join(absOut, "helios-introspect.json")
	var catalogJSON []byte
	if !opts.SkipBuild {
		catalogJSON, err = exec.CommandContext(ctx, latheOut, "commands", "--json").Output()
		if err != nil {
			return GenerateResult{}, fmt.Errorf("lathe commands --json: %w", err)
		}
		if err := os.WriteFile(catalogPath, catalogJSON, 0o644); err != nil {
			return GenerateResult{}, err
		}
		intro, err := IntrospectFromCatalogJSON(catalogJSON)
		if err != nil {
			return GenerateResult{}, err
		}
		introRaw, err := json.MarshalIndent(intro, "", "  ")
		if err != nil {
			return GenerateResult{}, err
		}
		introRaw = append(introRaw, '\n')
		if err := os.WriteFile(introPath, introRaw, 0o644); err != nil {
			return GenerateResult{}, err
		}
	}

	wrapDir := filepath.Join(absOut, "helios-wrap")
	if err := writeWrapper(wrapDir, opts.Name, filepath.Base(latheOut)); err != nil {
		return GenerateResult{}, err
	}

	readme := fmt.Sprintf("# %s\n\nGenerated by `helios-factory --engine=lathe` (Lathe %s).\n\n"+
		"## Build\n\n```bash\ncd %s\ngo build -o bin/%s.lathe ./cmd/%s\ngo build -o bin/%s ./helios-wrap\n```\n\n"+
		"Register the **wrapper** binary (`bin/%s`) with Helios — it provides `introspect` and proxies to the Lathe CLI.\n\n"+
		"## Agent notes\n\n- Lathe native: `commands --json`, `search`, `--dry-run`, `-o json`\n"+
		"- Helios: `introspect` via wrapper\n"+
		"- Install Lathe: `%s`\n",
		opts.Name, PinVersion, absOut, opts.Name, opts.Name, opts.Name, opts.Name, InstallHint)
	if err := writeFile(filepath.Join(absOut, "README.md"), readme); err != nil {
		return GenerateResult{}, err
	}
	provenance, _ := json.MarshalIndent(map[string]any{
		"engine":      "lathe",
		"lathePin":    PinVersion,
		"cliName":     opts.Name,
		"openapi":     absOpenAPI,
		"generatedAt": time.Now().UTC().Format(time.RFC3339),
	}, "", "  ")
	_ = os.WriteFile(filepath.Join(absOut, "helios-factory.json"), append(provenance, '\n'), 0o644)

	return GenerateResult{
		OutDir:      absOut,
		LatheBinary: latheOut,
		WrapBinary:  wrapDir,
		Introspect:  introPath,
		CatalogJSON: catalogPath,
		CLIName:     opts.Name,
	}, nil
}

func writeWrapper(dir, cliName, latheBinName string) error {
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return err
	}
	src := `// Code generated by helios-factory (engine=lathe). DO NOT EDIT.
package main

import (
	"encoding/json"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"syscall"
)

func main() {
	if len(os.Args) < 2 {
		fmt.Fprintf(os.Stderr, "usage: ` + cliName + ` <command>\n")
		os.Exit(2)
	}
	self, err := os.Executable()
	if err != nil {
		fail(err)
	}
	root := filepath.Clean(filepath.Join(filepath.Dir(self), ".."))
	switch os.Args[1] {
	case "introspect":
		raw, err := os.ReadFile(filepath.Join(root, "helios-introspect.json"))
		if err != nil {
			fail(err)
		}
		var v any
		if err := json.Unmarshal(raw, &v); err != nil {
			fail(err)
		}
		enc := json.NewEncoder(os.Stdout)
		enc.SetEscapeHTML(false)
		_ = enc.Encode(v)
		return
	case "--version", "version":
		fmt.Println("0.1.0")
		return
	}
	latheBin := filepath.Join(root, "bin", "` + latheBinName + `")
	cmd := exec.Command(latheBin, os.Args[1:]...)
	cmd.Stdin = os.Stdin
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	cmd.Env = os.Environ()
	if err := cmd.Run(); err != nil {
		if ee, ok := err.(*exec.ExitError); ok {
			if st, ok := ee.Sys().(syscall.WaitStatus); ok {
				os.Exit(st.ExitStatus())
			}
			os.Exit(ee.ExitCode())
		}
		fail(err)
	}
}

func fail(err error) {
	fmt.Fprintf(os.Stderr, "helios-lathe-wrap: %v\n", err)
	os.Exit(1)
}
`
	return writeFile(filepath.Join(dir, "main.go"), src)
}

func run(ctx context.Context, dir, name string, args ...string) error {
	cmd := exec.CommandContext(ctx, name, args...)
	cmd.Dir = dir
	var buf bytes.Buffer
	cmd.Stdout = &buf
	cmd.Stderr = &buf
	if err := cmd.Run(); err != nil {
		return fmt.Errorf("%s %v: %w\n%s", name, args, err, buf.String())
	}
	return nil
}

func writeFile(path, content string) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	return os.WriteFile(path, []byte(content), 0o644)
}

func extOf(path string) string {
	ext := filepath.Ext(path)
	if ext == "" {
		return ".yaml"
	}
	return ext
}
