package clifactory

import (
	"bytes"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"text/template"
)

type GenerateResult struct {
	OutDir      string
	MainGo      string
	SkillMD     string
	ReadmeMD    string
	FactoryJSON string
}

func Generate(spec Spec, outDir string) (GenerateResult, error) {
	norm, err := NormalizeSpec(spec)
	if err != nil {
		return GenerateResult{}, err
	}
	if err := os.MkdirAll(outDir, 0o755); err != nil {
		return GenerateResult{}, err
	}

	mainSrc, err := renderMain(norm)
	if err != nil {
		return GenerateResult{}, err
	}
	skill := renderSkill(norm)
	readme := renderReadme(norm)
	specRaw, err := json.MarshalIndent(norm, "", "  ")
	if err != nil {
		return GenerateResult{}, err
	}
	specRaw = append(specRaw, '\n')

	mainPath := filepath.Join(outDir, "main.go")
	skillPath := filepath.Join(outDir, "SKILL.md")
	readmePath := filepath.Join(outDir, "README.md")
	factoryPath := filepath.Join(outDir, "factory.json")

	if err := os.WriteFile(mainPath, []byte(mainSrc), 0o644); err != nil {
		return GenerateResult{}, err
	}
	if err := os.WriteFile(skillPath, []byte(skill), 0o644); err != nil {
		return GenerateResult{}, err
	}
	if err := os.WriteFile(readmePath, []byte(readme), 0o644); err != nil {
		return GenerateResult{}, err
	}
	if err := os.WriteFile(factoryPath, specRaw, 0o644); err != nil {
		return GenerateResult{}, err
	}

	return GenerateResult{
		OutDir:      outDir,
		MainGo:      mainPath,
		SkillMD:     skillPath,
		ReadmeMD:    readmePath,
		FactoryJSON: factoryPath,
	}, nil
}

type mainData struct {
	Name      string
	Version   string
	BaseURL   string
	EnvBase   string
	IntroJSON string
	Resources []string
	Commands  []Command
}

func renderMain(spec Spec) (string, error) {
	intro, err := json.MarshalIndent(spec.ToIntrospect(), "", "\t")
	if err != nil {
		return "", err
	}
	resSet := map[string]struct{}{}
	for _, c := range spec.Commands {
		resSet[c.Resource] = struct{}{}
	}
	resources := make([]string, 0, len(resSet))
	for r := range resSet {
		resources = append(resources, r)
	}
	sort.Strings(resources)

	useHTTP := strings.TrimSpace(spec.BaseURL) != ""
	for _, c := range spec.Commands {
		if strings.HasPrefix(c.Handler, "http") {
			useHTTP = true
			break
		}
	}

	data := mainData{
		Name:      spec.Name,
		Version:   spec.Version,
		BaseURL:   strings.TrimRight(spec.BaseURL, "/"),
		EnvBase:   strings.ToUpper(strings.ReplaceAll(spec.Name, "-", "_")) + "_BASE_URL",
		IntroJSON: string(intro),
		Resources: resources,
		Commands:  spec.Commands,
	}
	src := storeMainTemplate
	if useHTTP {
		src = httpMainTemplate
	}
	tmpl, err := template.New("main").Funcs(template.FuncMap{
		"joinPath": joinPath,
		"title":    titleIdent,
	}).Parse(src)
	if err != nil {
		return "", err
	}
	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		return "", err
	}
	return buf.String(), nil
}

func titleIdent(s string) string {
	if s == "" {
		return "X"
	}
	parts := strings.Split(s, "-")
	var b strings.Builder
	for _, p := range parts {
		if p == "" {
			continue
		}
		b.WriteString(strings.ToUpper(p[:1]))
		if len(p) > 1 {
			b.WriteString(p[1:])
		}
	}
	return b.String()
}

func renderSkill(spec Spec) string {
	var b strings.Builder
	fmt.Fprintf(&b, "# %s\n\n", spec.Name)
	if spec.Description != "" {
		fmt.Fprintf(&b, "%s\n\n", spec.Description)
	}
	b.WriteString("Factory-generated Helios CLI. Prefer commands from `introspect`.\n\n## Commands\n\n")
	for _, c := range spec.Commands {
		fmt.Fprintf(&b, "- `%s` (%s)\n", joinPath(c.Path), c.SideEffect)
	}
	b.WriteString("\n## Notes\n\n- Write commands support `--dry-run` (exit 9 on success).\n")
	b.WriteString("- Output is JSON envelope `{ok,command,data,error,meta}`.\n")
	if strings.TrimSpace(spec.BaseURL) != "" {
		fmt.Fprintf(&b, "- Default API base URL: `%s` (override with env `%s`).\n",
			strings.TrimRight(spec.BaseURL, "/"),
			strings.ToUpper(strings.ReplaceAll(spec.Name, "-", "_"))+"_BASE_URL")
	}
	return b.String()
}

func renderReadme(spec Spec) string {
	var b strings.Builder
	fmt.Fprintf(&b, "# %s\n\n", spec.Name)
	if spec.Description != "" {
		fmt.Fprintf(&b, "%s\n\n", spec.Description)
	}
	b.WriteString("Generated by `helios-factory`. Regenerate from `factory.json` instead of hand-editing `main.go`.\n\n")
	fmt.Fprintf(&b, "```bash\ngo build -o %s .\n./%s introspect\n```\n", spec.Name, spec.Name)
	return b.String()
}

func joinPath(parts []string) string {
	return strings.Join(parts, " ")
}

// storeMainTemplate: offline FileDB handlers (explicit offline / no servers in OpenAPI).
const storeMainTemplate = `// Code generated by helios-factory. DO NOT EDIT.
package main

import (
	"encoding/json"
	"fmt"
	"os"
	"time"

	"github.com/Duang777/helios/backend/internal/democli"
	"github.com/Duang777/helios/backend/internal/domain"
)

const version = "{{.Version}}"

func main() {
	if len(os.Args) < 2 {
		democli.Fail(2, "{{.Name}}", "usage: {{.Name}} <command>")
	}
	switch os.Args[1] {
	case "--version", "version":
		fmt.Println(version)
		return
	case "introspect":
		writeIntrospect()
		return
	default:
		handleResource(os.Args[1], os.Args[2:])
	}
}

func writeIntrospect() {
	var doc domain.CLIIntrospect
	raw := []byte({{printf "%q" .IntroJSON}})
	if err := json.Unmarshal(raw, &doc); err != nil {
		democli.Fail(1, "introspect", err.Error())
	}
	democli.WriteJSON(doc)
}

func handleResource(resource string, args []string) {
	switch resource {
{{- range .Resources}}
	case "{{.}}":
		handle{{title .}}(args)
{{- end}}
	default:
		democli.Fail(2, "{{.Name}}", "unknown command")
	}
}

{{- range $r := .Resources}}

func handle{{title $r}}(args []string) {
	if len(args) == 0 {
		democli.Fail(2, "{{$r}}", "missing subcommand")
	}
	db, err := democli.NewFileDB("{{$.Name}}-{{$r}}")
	if err != nil {
		democli.Fail(1, "{{$r}}", err.Error())
	}
	data := map[string]map[string]any{}
	_ = db.Load(&data)
	if data == nil {
		data = map[string]map[string]any{}
	}
	switch args[0] {
{{- range $.Commands}}
{{- if eq .Resource $r}}
{{- if eq .Handler "storeList"}}
	case "list":
		items := make([]map[string]any, 0, len(data))
		for _, v := range data {
			items = append(items, v)
		}
		democli.OK("{{joinPath .Path}}", map[string]any{"items": items}, map[string]any{"cli": "{{$.Name}}", "version": version})
{{- end}}
{{- if eq .Handler "storeGet"}}
	case "get":
		id := democli.RequireFlag(args[1:], "--id", "{{joinPath .Path}}")
		item, ok := data[id]
		if !ok {
			democli.Fail(3, "{{joinPath .Path}}", "not found")
		}
		democli.OK("{{joinPath .Path}}", item, map[string]any{"cli": "{{$.Name}}", "version": version})
{{- end}}
{{- if eq .Handler "storeCreate"}}
	case "create":
		raw := democli.RequireFlag(args[1:], "--from-json", "{{joinPath .Path}}")
		var item map[string]any
		if err := json.Unmarshal([]byte(raw), &item); err != nil {
			democli.Fail(2, "{{joinPath .Path}}", "invalid --from-json")
		}
		id, _ := item["id"].(string)
		if id == "" {
			id = fmt.Sprintf("item-%d", time.Now().UnixNano())
			item["id"] = id
		}
		if democli.HasFlag(args[1:], "--dry-run") {
			item["status"] = "dry-run"
			democli.OK("{{joinPath .Path}}", item, map[string]any{"cli": "{{$.Name}}", "dryRun": true, "version": version})
			os.Exit(9)
		}
		item["status"] = "created"
		item["createdAt"] = time.Now().UTC().Format(time.RFC3339)
		data[id] = item
		if err := db.Save(data); err != nil {
			democli.Fail(1, "{{joinPath .Path}}", err.Error())
		}
		democli.OK("{{joinPath .Path}}", item, map[string]any{"cli": "{{$.Name}}", "version": version})
{{- end}}
{{- end}}
{{- end}}
	default:
		democli.Fail(2, "{{$r}}", "unknown subcommand")
	}
}
{{- end}}
`

// httpMainTemplate: real HTTP client against OpenAPI servers / baseUrl.
const httpMainTemplate = `// Code generated by helios-factory. DO NOT EDIT.
package main

import (
	"bytes"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"os"
	"strings"
	"time"

	"github.com/Duang777/helios/backend/internal/democli"
	"github.com/Duang777/helios/backend/internal/domain"
)

const version = "{{.Version}}"
const defaultBaseURL = "{{.BaseURL}}"

func main() {
	if len(os.Args) < 2 {
		democli.Fail(2, "{{.Name}}", "usage: {{.Name}} <command>")
	}
	switch os.Args[1] {
	case "--version", "version":
		fmt.Println(version)
		return
	case "introspect":
		writeIntrospect()
		return
	default:
		handleResource(os.Args[1], os.Args[2:])
	}
}

func baseURL() string {
	if v := strings.TrimSpace(os.Getenv("{{.EnvBase}}")); v != "" {
		return strings.TrimRight(v, "/")
	}
	return defaultBaseURL
}

func writeIntrospect() {
	var doc domain.CLIIntrospect
	raw := []byte({{printf "%q" .IntroJSON}})
	if err := json.Unmarshal(raw, &doc); err != nil {
		democli.Fail(1, "introspect", err.Error())
	}
	democli.WriteJSON(doc)
}

func handleResource(resource string, args []string) {
	switch resource {
{{- range .Resources}}
	case "{{.}}":
		handle{{title .}}(args)
{{- end}}
	default:
		democli.Fail(2, "{{.Name}}", "unknown command")
	}
}

func httpJSON(method, path string, body any) (int, map[string]any, error) {
	var rdr io.Reader
	if body != nil {
		raw, err := json.Marshal(body)
		if err != nil {
			return 0, nil, err
		}
		rdr = bytes.NewReader(raw)
	}
	req, err := http.NewRequest(method, baseURL()+path, rdr)
	if err != nil {
		return 0, nil, err
	}
	if body != nil {
		req.Header.Set("Content-Type", "application/json")
	}
	client := &http.Client{Timeout: 30 * time.Second}
	resp, err := client.Do(req)
	if err != nil {
		return 0, nil, err
	}
	defer resp.Body.Close()
	raw, err := io.ReadAll(resp.Body)
	if err != nil {
		return resp.StatusCode, nil, err
	}
	var out map[string]any
	if len(raw) > 0 {
		if err := json.Unmarshal(raw, &out); err != nil {
			return resp.StatusCode, nil, fmt.Errorf("invalid json from API: %w", err)
		}
	}
	if out == nil {
		out = map[string]any{}
	}
	return resp.StatusCode, out, nil
}

{{- range $r := .Resources}}

func handle{{title $r}}(args []string) {
	if len(args) == 0 {
		democli.Fail(2, "{{$r}}", "missing subcommand")
	}
	switch args[0] {
{{- range $.Commands}}
{{- if eq .Resource $r}}
{{- if or (eq .Handler "httpList") (eq .Handler "storeList")}}
	case "list":
		code, data, err := httpJSON("GET", "/{{$r}}", nil)
		if err != nil {
			democli.Fail(1, "{{joinPath .Path}}", err.Error())
		}
		if code >= 300 {
			democli.Fail(1, "{{joinPath .Path}}", fmt.Sprintf("API status %d: %v", code, data["error"]))
		}
		democli.OK("{{joinPath .Path}}", data, map[string]any{"cli": "{{$.Name}}", "version": version, "baseUrl": baseURL()})
{{- end}}
{{- if or (eq .Handler "httpGet") (eq .Handler "storeGet")}}
	case "get":
		id := democli.RequireFlag(args[1:], "--id", "{{joinPath .Path}}")
		code, data, err := httpJSON("GET", "/{{$r}}/"+id, nil)
		if err != nil {
			democli.Fail(1, "{{joinPath .Path}}", err.Error())
		}
		if code == 404 {
			democli.Fail(3, "{{joinPath .Path}}", "not found")
		}
		if code >= 300 {
			democli.Fail(1, "{{joinPath .Path}}", fmt.Sprintf("API status %d: %v", code, data["error"]))
		}
		democli.OK("{{joinPath .Path}}", data, map[string]any{"cli": "{{$.Name}}", "version": version, "baseUrl": baseURL()})
{{- end}}
{{- if or (eq .Handler "httpCreate") (eq .Handler "storeCreate")}}
	case "create":
		raw := democli.RequireFlag(args[1:], "--from-json", "{{joinPath .Path}}")
		var item map[string]any
		if err := json.Unmarshal([]byte(raw), &item); err != nil {
			democli.Fail(2, "{{joinPath .Path}}", "invalid --from-json")
		}
		if democli.HasFlag(args[1:], "--dry-run") {
			item["status"] = "dry-run"
			democli.OK("{{joinPath .Path}}", item, map[string]any{"cli": "{{$.Name}}", "dryRun": true, "version": version, "baseUrl": baseURL()})
			os.Exit(9)
		}
		code, data, err := httpJSON("POST", "/{{$r}}", item)
		if err != nil {
			democli.Fail(1, "{{joinPath .Path}}", err.Error())
		}
		if code >= 300 {
			democli.Fail(1, "{{joinPath .Path}}", fmt.Sprintf("API status %d: %v", code, data["error"]))
		}
		democli.OK("{{joinPath .Path}}", data, map[string]any{"cli": "{{$.Name}}", "version": version, "baseUrl": baseURL()})
{{- end}}
{{- end}}
{{- end}}
	default:
		democli.Fail(2, "{{$r}}", "unknown subcommand")
	}
}
{{- end}}
`

