// Code generated by helios-factory. DO NOT EDIT.
package main

import (
	"bytes"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"os"
	"strings"
	"time"

	"github.com/Duang777/helios/backend/internal/democli"
	"github.com/Duang777/helios/backend/internal/domain"
)

const version = "0.1.0"
const defaultBaseURL = "http://127.0.0.1:8795"

func main() {
	if len(os.Args) < 2 {
		democli.Fail(2, "demo-inventory", "usage: demo-inventory <command>")
	}
	switch os.Args[1] {
	case "--version", "version":
		fmt.Println(version)
		return
	case "introspect":
		writeIntrospect()
		return
	default:
		handleResource(os.Args[1], os.Args[2:])
	}
}

func baseURL() string {
	if v := strings.TrimSpace(os.Getenv("DEMO_INVENTORY_BASE_URL")); v != "" {
		return strings.TrimRight(v, "/")
	}
	return defaultBaseURL
}

func writeIntrospect() {
	var doc domain.CLIIntrospect
	raw := []byte("{\n\t\"name\": \"demo-inventory\",\n\t\"version\": \"0.1.0\",\n\t\"commands\": [\n\t\t{\n\t\t\t\"path\": [\n\t\t\t\t\"items\",\n\t\t\t\t\"create\"\n\t\t\t],\n\t\t\t\"sideEffect\": \"write\",\n\t\t\t\"dryRun\": true,\n\t\t\t\"args\": [\n\t\t\t\t{\n\t\t\t\t\t\"name\": \"--from-json\",\n\t\t\t\t\t\"type\": \"json\",\n\t\t\t\t\t\"required\": true\n\t\t\t\t},\n\t\t\t\t{\n\t\t\t\t\t\"name\": \"--dry-run\",\n\t\t\t\t\t\"type\": \"boolean\"\n\t\t\t\t},\n\t\t\t\t{\n\t\t\t\t\t\"name\": \"--output\",\n\t\t\t\t\t\"type\": \"string\",\n\t\t\t\t\t\"enum\": [\n\t\t\t\t\t\t\"json\"\n\t\t\t\t\t],\n\t\t\t\t\t\"default\": \"json\"\n\t\t\t\t}\n\t\t\t]\n\t\t},\n\t\t{\n\t\t\t\"path\": [\n\t\t\t\t\"items\",\n\t\t\t\t\"get\"\n\t\t\t],\n\t\t\t\"sideEffect\": \"read\",\n\t\t\t\"args\": [\n\t\t\t\t{\n\t\t\t\t\t\"name\": \"--id\",\n\t\t\t\t\t\"type\": \"string\",\n\t\t\t\t\t\"required\": true\n\t\t\t\t},\n\t\t\t\t{\n\t\t\t\t\t\"name\": \"--output\",\n\t\t\t\t\t\"type\": \"string\",\n\t\t\t\t\t\"enum\": [\n\t\t\t\t\t\t\"json\"\n\t\t\t\t\t],\n\t\t\t\t\t\"default\": \"json\"\n\t\t\t\t}\n\t\t\t]\n\t\t},\n\t\t{\n\t\t\t\"path\": [\n\t\t\t\t\"items\",\n\t\t\t\t\"list\"\n\t\t\t],\n\t\t\t\"sideEffect\": \"read\"\n\t\t},\n\t\t{\n\t\t\t\"path\": [\n\t\t\t\t\"introspect\"\n\t\t\t],\n\t\t\t\"sideEffect\": \"none\"\n\t\t}\n\t]\n}")
	if err := json.Unmarshal(raw, &doc); err != nil {
		democli.Fail(1, "introspect", err.Error())
	}
	democli.WriteJSON(doc)
}

func handleResource(resource string, args []string) {
	switch resource {
	case "items":
		handleItems(args)
	default:
		democli.Fail(2, "demo-inventory", "unknown command")
	}
}

func httpJSON(method, path string, body any) (int, map[string]any, error) {
	var rdr io.Reader
	if body != nil {
		raw, err := json.Marshal(body)
		if err != nil {
			return 0, nil, err
		}
		rdr = bytes.NewReader(raw)
	}
	req, err := http.NewRequest(method, baseURL()+path, rdr)
	if err != nil {
		return 0, nil, err
	}
	if body != nil {
		req.Header.Set("Content-Type", "application/json")
	}
	client := &http.Client{Timeout: 30 * time.Second}
	resp, err := client.Do(req)
	if err != nil {
		return 0, nil, err
	}
	defer resp.Body.Close()
	raw, err := io.ReadAll(resp.Body)
	if err != nil {
		return resp.StatusCode, nil, err
	}
	var out map[string]any
	if len(raw) > 0 {
		if err := json.Unmarshal(raw, &out); err != nil {
			return resp.StatusCode, nil, fmt.Errorf("invalid json from API: %w", err)
		}
	}
	if out == nil {
		out = map[string]any{}
	}
	return resp.StatusCode, out, nil
}

func handleItems(args []string) {
	if len(args) == 0 {
		democli.Fail(2, "items", "missing subcommand")
	}
	switch args[0] {
	case "create":
		raw := democli.RequireFlag(args[1:], "--from-json", "items create")
		var item map[string]any
		if err := json.Unmarshal([]byte(raw), &item); err != nil {
			democli.Fail(2, "items create", "invalid --from-json")
		}
		if democli.HasFlag(args[1:], "--dry-run") {
			item["status"] = "dry-run"
			democli.OK("items create", item, map[string]any{"cli": "demo-inventory", "dryRun": true, "version": version, "baseUrl": baseURL()})
			os.Exit(9)
		}
		code, data, err := httpJSON("POST", "/items", item)
		if err != nil {
			democli.Fail(1, "items create", err.Error())
		}
		if code >= 300 {
			democli.Fail(1, "items create", fmt.Sprintf("API status %d: %v", code, data["error"]))
		}
		democli.OK("items create", data, map[string]any{"cli": "demo-inventory", "version": version, "baseUrl": baseURL()})
	case "get":
		id := democli.RequireFlag(args[1:], "--id", "items get")
		code, data, err := httpJSON("GET", "/items/"+id, nil)
		if err != nil {
			democli.Fail(1, "items get", err.Error())
		}
		if code == 404 {
			democli.Fail(3, "items get", "not found")
		}
		if code >= 300 {
			democli.Fail(1, "items get", fmt.Sprintf("API status %d: %v", code, data["error"]))
		}
		democli.OK("items get", data, map[string]any{"cli": "demo-inventory", "version": version, "baseUrl": baseURL()})
	case "list":
		code, data, err := httpJSON("GET", "/items", nil)
		if err != nil {
			democli.Fail(1, "items list", err.Error())
		}
		if code >= 300 {
			democli.Fail(1, "items list", fmt.Sprintf("API status %d: %v", code, data["error"]))
		}
		democli.OK("items list", data, map[string]any{"cli": "demo-inventory", "version": version, "baseUrl": baseURL()})
	default:
		democli.Fail(2, "items", "unknown subcommand")
	}
}
